site_name: Duon Theme
dev_addr: localhost:7371
extra:
  project: Duon
copyright: © 2022-2024 ebene fünf GmbH
theme:
  name: duon
repo_url: https://github.com/duon/mkdocs-theme
markdown_extensions:
  - admonition
  - pymdownx.snippets:
      base_path: ["docs/code"]